---
driver:
  name: vagrant
  synced_folders:
    - ['../../../search-app/target', '/tmp']

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0

platforms:
  - name: centos-7.2

suites:
  - name: default
    driver_config:
      network:
        - ["forwarded_port", {guest: 8080, host: 8080}]
        - ["forwarded_port", {guest: 8443, host: 8443}]
    run_list:
      - recipe[tomcat::default]
